# Generated by Django 5.2 on 2026-06-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
